### ISSUE TITLE
Everlasting "Scheduling next jump"

### ISSUE THREAD

**Issue by MrWho666** [pilotso11/fc-macros#1]
Yesterday all worked successfully. I wathced, how my carrier complite 2 jumps with marco. But after that, unfortunately, there was a bug, 
because of which selection of carrier services option dissapired (u need press 2 or 3 to fix that). And macro just stopped. After that, i tried to add option, which llbe press "2" before "schedule_jump". Well, that was terrible, so i had to reinstall fcmacros. So, after that, after i deleted all files, related with fcmacros (all fcmacros regedit files too), and installed it again, script just stuck at "Scheduling next jump". I know, fcmacro creates folders at %localappdata%, but, maybe, is there something else?
Yeap, and one more problem:
carrier_management original .jpg didnt work in odyssey for me. Macro just doesn't see it. So i just took a screenshot with carrier management and replace it. Worked for me.                                            
Sorry for my englins mistakes.

**Comment by pilotso11** [comment]
Thank you for the feedback.   It's cool that you're trying it out.

As you've spotted - its REALLY sensitive to the size of the HUD.  It already tries several, but it looks to be almost ship specific. If you can send me your screenshot I'll add it to the collection of images it is checking.   

On the other one, to work around the not-selectable bug after a jump it is already trying to move the the left or right window and back.  If that didn't work i wonder if the timing was just too fast on your setup.   At line 143 of fcmacros.py there is a "sleep(5)" - which waits 5 seconds after the jump.   And then it calls "press(ED_RIGHT_WINDOW)" which should be selecting the right pane.     You could try increasing that sleep from 5 to 10 seconds (or longer) and see if that helps?  Alternatively, you might add a second "sleep(5) and a second call to "press(ED_RIGHT_WINDOW)".     If either of those work I think we could make the macro loop and retry the select right window a few times before looking to return to the main HUD and proceeding.

Thanks

**Comment by pilotso11** [comment]
Oh.  You're on the exercise version.  (First time bundling python as an exe).  I'll need to update the delay in there or expose it as a setting.  Will get back to you with that.

**Comment by MrWho666** [comment]
![5](https://user-images.githubusercontent.com/99964615/154772014-60849b0a-3bd8-4f3d-a5e8-fb7bfe777b86.png)
Soo... Do you know what the problem is?

**Comment by pilotso11** [comment]
This looks to be a bug if the current system isn't in the route file.  It fails silently.
I've uploaded a new version 0.1.2.  It fixes that issue issue and a few others:
0.1.2 also adds an option to turn on a debug log which will show details of every step its taking.     This is a checkbox on the bottom.
It will now be a bit more aggressive after a jump trying to kick start the HUD menu.    Trying up to 10 times to open the right HUD screen.
It's also added a sanity check that E:D has the focus before it runs a macro.
Hopefully these help!
